### PR TITLE
getDbCohortBasedCovariatesData BigQuery support

### PR DESCRIPTION
**Pull request by ginberg**
see #208

### CODE REVIEW

**Comment by ginberg** [comment]
@cyanover can you confirm if this change works for you? Unfortunately we don't have a BQ test environment

**Comment by cyanover** [comment]
Not yet ... there's at least one more place that requires casting, under Reference construction (in both 
CohortBasedBinaryCovariates.sql and CohortBasedCountCovariates.sql): 

`	ON **CAST(**cohort_id **AS INT)** = CAST((covariate_id - @analysis_id) / 1000 AS INT);
`

**Comment by ginberg** [comment]
@cyanover ok, this is adjusted, could you try again?

**Comment by cyanover** [comment]
Yep, that works. Thanks!

**Pull request merged**
