### PR TITLE
Impala

### PR DESCRIPTION
**Pull request by korneliusracz**

### CODE REVIEW

**Comment by schuemie** [comment]
Could you help me understand: why the cast to VARCHAR(512)?

**Comment by korneliusracz** [comment]
Thanks for pointing that out. I changed it to the more general VARCHAR, and
committed the change.

Cornelius

**Comment by schuemie** [comment]
Still just trying to understand: isn't the result of CONCAT by definition a VARCHAR? Why cast at all?

**Comment by korneliusracz** [comment]
CONCAT() in Impala and MS SQL returns STRING. However, covariate_name in
table #cov_ref in GetCovariates.sql is defined as VARCHAR.

Thanks.

**Comment by schuemie** [comment]
Ehhh, nope. CONCAT returns a VARCHAR on MS SQL Server, and there is no STRING type in MS SQL Server. This seems to be something specific to Impala. Could you tell me what the difference is between STRING and VARCHAR in Impala? I can't seem to find information on the difference.

Since this appears to be an Impala-specific thing, wouldn't Impala automatically cast the STRING to VARCHAR when inserting the data?

I'm just trying to figure out if we can lose the VARCHAR, and move the change to CONCAT to SqlRender so we've solved this problem for all OHDSI applications in one go.

**Comment by korneliusracz** [comment]
True, I misread the sql server documentation regarding CONCAT()  - I am
mostly using Impala/Hive.

You were correct: all the casting to VARCHAR is unnecessary. Instead, I had
to change the type in the table definition of #cov_ref in GetCovariates.sql
from VARCHAR(512) to simply VARCHAR. Now this .sql script can be run in
both sql server and impala.

Besides, the CONCAT()s make for better readability of the code than the "+".

Your thoughts? Thanks.

Cornelius

**Comment by schuemie** [comment]
Thanks! I agree, the CONCATs do look a lot nicer.

I'm testing your PR, but have hit something weird: your code seems to be based on an old version, even though it should be up-to-date. One specific thing I notice (that breaks the code) is that your code still contains a mention of `@use_covariate_observation_below` [here](https://github.com/korneliusracz/FeatureExtraction/blob/impala/inst/sql/sql_server/GetCovariates.sql#L3314) that has long since been replaced with `@use_covariate_measurement_below` as seen [here](https://github.com/OHDSI/FeatureExtraction/blob/master/inst/sql/sql_server/GetCovariates.sql#L3315). Could you check why you're not really up to date with master?

**Comment by korneliusracz** [comment]
I made the changes regarding @use_covariate_observation_below and
committed. Please check.
Thanks.

Cornelius

**Pull request merged**
