### PR TITLE
Support Impala in version 2

### PR DESCRIPTION
**Pull request by tomwhite**
@schuemie These changes allow the testthat tests to pass. There are some more things (e.g. in GetHdpsCovariates.sql) that will need extra casts - are they covered by any tests yet?

### CODE REVIEW

**Comment by schuemie** [comment]
Great! I will  make sure future SQL I write includes the necessary casts. 
Don't worry about GetHdpsCovariates. That is included for methods research purposes, and unlikely to be used in normal studies.

**Comment by tomwhite** [comment]
Thanks @schuemie! I noticed that [the Travis build failed](https://travis-ci.org/OHDSI/FeatureExtraction/builds/297932221?utm_source=github_status&utm_medium=notification) though - should testOnImpala.R be removed or disabled for the time being?

**Comment by schuemie** [comment]
Hi @tomwhite . I've already added a check to see if the Impala environment variables are set: https://github.com/OHDSI/FeatureExtraction/commit/6707c66a30ee34c87bf182923a972755ec2a6934

The reason the checks are currently failing is because the Oracle and Postgres test servers are too slow. I'm looking into it.

**Comment by tomwhite** [comment]
Great - glad you've got it under control

**Pull request merged**
